name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run containers
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run pytest on backend container
        run: docker-compose -f docker-compose.yml exec flask-middleware pytest /app/backend/tests

      - name: Run frontend test on frontend container
        run: docker-compose -f docker-compose.yml exec react-frontend npm test -- --watchAll=false

      - name: Tear down
        run: docker-compose -f docker-compose.yml down